package com.epam.libraray_service.client;

import com.epam.libraray_service.dto.BookDto;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@FeignClient(name = "BOOK-SERVICE")
public interface BookFeignCLient {

    @GetMapping("/books")
    public ResponseEntity<List<BookDto>> getAllBooks();


    @GetMapping("/books/{id}")
    public ResponseEntity<BookDto> getSpecificBook(@PathVariable int id);


    // use cannot give id from json as it is getting autogenerated from identity property
    @PostMapping("/books")
    public  ResponseEntity<BookDto> addBook(@RequestBody BookDto book);


    //here u have to give specific id whihc u want to update
    @PutMapping("/books/{id}")
    public ResponseEntity<String> updateBook(@PathVariable int id,@RequestBody BookDto book);

    @DeleteMapping("/books/{id}")
    public ResponseEntity<String> deleteBook(@PathVariable int id);

}
